"""
Mock provider for local/staging smoke tests without external LLM dependency.
"""

from app.ai.providers.base import BaseLLMProvider, LLMResponse


class MockProvider(BaseLLMProvider):
    def __init__(self, model: str | None = None) -> None:
        self.model = model or "mock-llm"

    async def generate(self, prompt: str, **kwargs) -> LLMResponse:
        text = (
            "Mock assistant response: I can help with product discovery and support. "
            "This response is generated by the local mock provider for staging validation."
        )
        return LLMResponse(
            text=text,
            model=self.model,
            prompt_tokens=0,
            completion_tokens=0,
            total_tokens=0,
        )

    async def embed(self, text: str) -> list[float]:
        return [0.0, 0.0, 0.0]
